### ISSUE TITLE
Migrate tests to new location in the repo

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-idp#10]
There are tests in /bedrock/test that need to be migrated to the /tests/mocha and /tests/protractor folder.  Some tests have already been migrated.  The tests will need to be fixed-up to work with the current library.

**Comment by dlongley** [comment]
When doing this, we should also consider breaking them out into more than a single file. That makes it easier to pick and choose tests to run from the command line and keeps them scope limited which may help us manage and maintain them more easily.

**Comment by mattcollier** [comment]
This has been completed.
