### ISSUE TITLE
Increase passcode length

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/bedrock-idp#14]

**Comment by mattcollier** [comment]
Resolved via https://github.com/digitalbazaar/bedrock-idp/commit/d03d0810872878419c8c4d2f7f13f443dd3feb7f

**Comment by dlongley** [comment]
This issue concerns the `passcode` not the `password`:

https://github.com/digitalbazaar/bedrock-idp/blob/master/schemas/passcode.js

We still need to increase the length.

**Comment by mattcollier** [comment]
Resolved in bedrock-authn-password module.
