### ISSUE TITLE
Ensure pending POST requests are handled after login

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-idp#2]
When a POST request arrives that requires login, ensure it gets handled/re-POSTed after login. This may need to be done in a different module but making a note of it here.

**Comment by dlongley** [comment]
Also take into consideration CSRF issues ... if we re-POST from the local site that may obscure attacks and make them easier.

**Comment by mattcollier** [comment]
I found this article discussing the use of req.session for storing data prior to authentication: https://www.airpair.com/express/posts/expressjs-and-passportjs-sessions-deep-dive

Do you think adding this sort of functionality to bedrock-passport.ensureAuthenticated, or a new function there) would be a viable option?

**Comment by dlongley** [comment]
> Do you think adding this sort of functionality to bedrock-passport.ensureAuthenticated, or a new function there) would be a viable option?

Yeah, that's one way we could do it.

**Comment by dlongley** [comment]
During an authorization.io flow, we need to do authentication w/o navigating away from the page and losing the API request.

**Comment by dlongley** [comment]
For the auth.io flow fix:

1. Let `credential-task` page load. Get the pending operation via the JS API (like we do already).
2. For a credentials request, auth will fail when trying to handle the query.
3. For a storage request, look at DID in the storage request and make some kind of session check request to see if user is authenticated or not.
4. Use a login directive to display a form for the user to login. It will make a background ($http) post call w/username/password/DID/whatever auth request.
5. On login success, handle the actual request.

The above all happens on the same page without any need for special caches or redirects. We could do an angular route redirection to the login page if that's cleaner for some reason. Either should be a reasonably good UX.
