### ISSUE TITLE
Can't load settings page due to TypeError

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-idp#31]
TypeError: Cannot read property 'email' of null

On this line of identity-settings-controller:

md.update(brIdentityService.identity.email, 'utf8');

**Comment by mattcollier** [comment]
this may be fixed already.  You have fresh install as of today?  Also, is this a DID user or a local identity?

**Comment by dlongley** [comment]
Pretty sure it was a fresh install? It was a brand new DID user I created.

**Comment by davidlehn** [comment]
Happened to me too.  But only right after creating the DID on authio and going straight to the settings.  Just refreshing the settings page fixes it.

**Comment by mattcollier** [comment]
This is repeatable when going to settings immediately after joining the IdP.
